# Generated by Django 6.0.5 on 2026-06-01 12:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('resume', models.CharField(max_length=280)),
                ('contenu', models.TextField()),
                ('auteur', models.CharField(default='Equipe du livret', max_length=120)),
                ('image', models.FileField(blank=True, upload_to='articles/')),
                ('publie', models.BooleanField(default=True)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='journal.categorie')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
