# Generated by Django 6.0.5 on 2026-06-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(default='Equipe SEAKE JOURNAL', max_length=120),
        ),
    ]
