# Generated by Django 6.0.5 on 2026-06-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_article_auteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePublicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=160)),
                ('nom_entreprise', models.CharField(blank=True, max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('type_produit', models.CharField(choices=[('page', 'Page publicitaire'), ('carte', "Carte d'affaire"), ('coupon', 'Coupon rabais'), ('reseaux', 'Campagne reseaux sociaux')], max_length=20)),
                ('budget', models.CharField(blank=True, max_length=80)),
                ('date_souhaitee', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('contacte', 'Client contacte'), ('acceptee', 'Acceptee'), ('refusee', 'Refusee')], default='nouvelle', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
