# Generated by Django 6.0.5 on 2026-06-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_article_test_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='articles/galerie/')),
                ('legende', models.CharField(blank=True, max_length=180)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='journal.article')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
