# Generated by Django 6.0.5 on 2026-06-02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0007_photoarticle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.FileField(
                blank=True,
                upload_to="articles/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "avif", "gif"],
                        message="Ajoutez une image valide: JPG, PNG, WEBP, AVIF ou GIF.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="photoarticle",
            name="image",
            field=models.FileField(
                upload_to="articles/galerie/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "avif", "gif"],
                        message="Ajoutez une image valide: JPG, PNG, WEBP, AVIF ou GIF.",
                    )
                ],
            ),
        ),
    ]
