# Generated by Django 6.0.5 on 2026-06-03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0008_alter_article_image_alter_photoarticle_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="publicite_bouton",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="article",
            name="publicite_image",
            field=models.FileField(
                blank=True,
                upload_to="articles/publicites/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "avif", "gif"],
                        message="Ajoutez une image valide: JPG, PNG, WEBP, AVIF ou GIF.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="publicite_lien",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="publicite_texte",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="publicite_titre",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
