# Generated by Django 6.0.5 on 2026-06-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_article_publicite_bouton_article_publicite_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EchantillonCouleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=160)),
                ('projet', models.CharField(max_length=180)),
                ('couleur', models.CharField(max_length=120)),
                ('reference', models.CharField(blank=True, help_text='Exemple: Pantone 485 C, CMYK, HEX ou reference client.', max_length=120)),
                ('hex_couleur', models.CharField(blank=True, help_text='Exemple: #D81818 pour afficher un apercu.', max_length=7)),
                ('cible_l', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cible_a', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cible_b', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mesure_l', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mesure_a', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mesure_b', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tolerance_delta_e', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('statut', models.CharField(choices=[('preparation', 'En preparation'), ('a_approuver', 'A approuver'), ('approuve', 'Approuve'), ('refuse', 'Refuse')], default='preparation', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Echantillon couleur',
                'verbose_name_plural': 'Echantillons couleur',
                'ordering': ['-date_modification'],
            },
        ),
    ]
