# Generated by Django 6.0.5 on 2026-06-10 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_echantilloncouleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantilloncouleur',
            name='blanc_soutien',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='echantilloncouleur',
            name='couches_blanc',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='echantilloncouleur',
            name='opacite_blanc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage optionnel, exemple: 85.00.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='echantilloncouleur',
            name='substrat',
            field=models.CharField(choices=[('papier_couche', 'Papier couche'), ('papier_non_couche', 'Papier non couche'), ('carton', 'Carton'), ('film', 'Film'), ('foil', 'Foil'), ('plastique', 'Plastique'), ('autre', 'Autre')], default='papier_couche', max_length=30),
        ),
        migrations.AddField(
            model_name='echantilloncouleur',
            name='surface',
            field=models.CharField(blank=True, help_text='Exemple: brillant, mat, metallise, transparent.', max_length=120),
        ),
        migrations.CreateModel(
            name='LectureCouleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=80)),
                ('mesure_l', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mesure_a', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mesure_b', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('commentaire', models.CharField(blank=True, max_length=180)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('echantillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='journal.echantilloncouleur')),
            ],
            options={
                'verbose_name': 'Lecture couleur',
                'verbose_name_plural': 'Lectures couleur',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
