# Generated by Django 6.0.5 on 2026-06-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_echantilloncouleur_blanc_soutien_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionFormule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Correction', max_length=120)),
                ('poids_batch', models.DecimalField(decimal_places=2, default=1000.0, max_digits=8)),
                ('pro_blue_ajout', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('green_ajout', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('trans_white_reduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('autre_correction', models.CharField(blank=True, max_length=180)),
                ('mesure_apres_l', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mesure_apres_a', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mesure_apres_b', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('echantillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='journal.echantilloncouleur')),
            ],
            options={
                'verbose_name': 'Correction formule',
                'verbose_name_plural': 'Corrections formule',
                'ordering': ['-date_creation'],
            },
        ),
    ]
