# Generated by Django 6.0.5 on 2026-06-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_clarify_photo_placement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoarticle',
            name='apres_paragraphe',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Exemple: 3 affiche la photo apres le 3e paragraphe. Pour un placement exact, ajoutez une ligne seule avec ce numero dans le texte de l'article. Laissez vide pour la galerie a la fin.", null=True, verbose_name='Afficher apres le paragraphe'),
        ),
    ]
