# Generated by Django 6.0.5 on 2026-08-29 13:06

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_demandepublicite_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoDuJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default="Aujourd'hui sur SEAKE", max_length=180)),
                ('sous_titre', models.TextField(blank=True, default='Les nouvelles, annonces, coupons, cours et services utiles au meme endroit pour garder la communaute branchee.')),
                ('photo', models.FileField(blank=True, help_text="Photo principale pour la page Aujourd'hui sur SEAKE.", upload_to='infos_du_jour/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif'], message='Ajoutez une image valide: JPG, PNG, WEBP, AVIF ou GIF.')])),
                ('meteo', models.CharField(blank=True, max_length=220)),
                ('trafic', models.CharField(blank=True, max_length=220)),
                ('evenement', models.CharField(blank=True, max_length=220)),
                ('alerte', models.CharField(blank=True, max_length=220)),
                ('message', models.TextField(blank=True)),
                ('publie', models.BooleanField(default=True)),
                ('date_affichage', models.DateField(default=django.utils.timezone.localdate)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Info du jour',
                'verbose_name_plural': 'Infos du jour',
                'ordering': ['-date_affichage', '-date_modification'],
            },
        ),
    ]
