# Generated by Django 6.0.5 on 2026-08-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_infodujour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepublicite',
            name='type_produit',
            field=models.CharField(choices=[('page', 'Page publicitaire'), ('premiere_page', 'Demi-page premiere page'), ('carte', "Carte d'affaire"), ('coupon', 'Coupon rabais'), ('reseaux', 'Campagne reseaux sociaux')], max_length=20),
        ),
    ]
