# Generated by Django 6.0.5 on 2026-09-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_alter_demandepublicite_type_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('souhaite_courriel', models.BooleanField(default=True)),
                ('souhaite_sms', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('site', 'Site web'), ('papier', 'Journal papier'), ('telephone', 'Telephone')], default='site', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abonne',
                'verbose_name_plural': 'Abonnes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
