# Generated by Django 6.0.5 on 2026-09-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_abonne'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseSondageElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=140)),
                ('enjeu_important', models.CharField(choices=[('sante', 'Sante'), ('logement', 'Logement'), ('economie', 'Economie'), ('education', 'Education'), ('securite', 'Securite'), ('environnement', 'Environnement'), ('autre', 'Autre')], max_length=30)),
                ('intention_vote', models.CharField(blank=True, choices=[('caq', 'CAQ'), ('plq', 'Parti liberal du Quebec'), ('pq', 'Parti quebecois'), ('qs', 'Quebec solidaire'), ('pcq', 'Parti conservateur du Quebec'), ('autre', 'Autre parti'), ('indecis', 'Indecis'), ('prefere_pas', 'Je prefere ne pas repondre')], max_length=30)),
                ('certitude', models.CharField(choices=[('tres', 'Tres certain'), ('assez', 'Assez certain'), ('peu', 'Pas encore certain'), ('indecis', 'Je suis encore indecis')], max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('veut_resultats', models.BooleanField(default=False, verbose_name='Souhaite recevoir les resultats')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reponse sondage election',
                'verbose_name_plural': 'Reponses sondage election',
                'ordering': ['-date_creation'],
            },
        ),
    ]
