# Generated by Django 6.0.5 on 2026-09-19 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def creer_premiere_question(apps, schema_editor):
    QuestionDuJour = apps.get_model('journal', 'QuestionDuJour')
    QuestionDuJour.objects.create(
        question='Quel sujet aimeriez-vous voir davantage sur SEAKE JOURNAL?',
        choix_1='Actualite locale',
        choix_2='Economie et cout de la vie',
        choix_3='Sport et culture',
        choix_4='Meteo et circulation',
        choix_5='Impression, couleur et prepresse',
        message='Choisissez le sujet qui vous interesse le plus.',
        active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0021_reponsesondageelection'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDuJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240)),
                ('choix_1', models.CharField(max_length=160)),
                ('choix_2', models.CharField(max_length=160)),
                ('choix_3', models.CharField(blank=True, max_length=160)),
                ('choix_4', models.CharField(blank=True, max_length=160)),
                ('choix_5', models.CharField(blank=True, max_length=160)),
                ('choix_6', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField(blank=True, help_text='Court texte affiche sous la question.')),
                ('active', models.BooleanField(default=True)),
                ('date_affichage', models.DateField(default=django.utils.timezone.localdate)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question du jour',
                'verbose_name_plural': 'Questions du jour',
                'ordering': ['-date_affichage', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQuestionDuJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.PositiveSmallIntegerField()),
                ('session', models.CharField(blank=True, max_length=40)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='journal.questiondujour')),
            ],
            options={
                'verbose_name': 'Reponse a la question du jour',
                'verbose_name_plural': 'Reponses aux questions du jour',
                'ordering': ['-date_creation'],
                'constraints': [models.UniqueConstraint(fields=('question', 'session'), name='une_reponse_par_session_et_question')],
            },
        ),
        migrations.RunPython(creer_premiere_question, migrations.RunPython.noop),
    ]
