# Generated by Django 6.0.5 on 2026-09-19 15:26

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_questiondujour_reponsequestiondujour'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sous_titre', models.CharField(blank=True, max_length=240)),
                ('numero_edition', models.CharField(help_text='Exemple: Volume 1, numero 1.', max_length=60)),
                ('date_publication', models.DateField(default=django.utils.timezone.localdate)),
                ('couverture', models.FileField(blank=True, upload_to='magazines/couvertures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif'], message='Ajoutez une image valide: JPG, PNG, WEBP, AVIF ou GIF.')])),
                ('editorial', models.TextField(blank=True)),
                ('nombre_pages', models.PositiveSmallIntegerField(default=8)),
                ('format_papier', models.CharField(choices=[('tabloid', 'Tabloid'), ('broadsheet', 'Grand format'), ('lettre', 'Lettre ou A4'), ('personnalise', 'Format personnalise')], default='tabloid', max_length=20)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pdf_numerique', models.FileField(blank=True, help_text="PDF leger pour la lecture a l'ecran.", upload_to='magazines/numeriques/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Ajoutez un fichier PDF valide.')])),
                ('pdf_presse', models.FileField(blank=True, help_text='PDF haute resolution valide pour le prépresse.', upload_to='magazines/presse/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Ajoutez un fichier PDF valide.')])),
                ('publie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, help_text='Choisissez les articles inclus dans ce numero.', related_name='numeros_magazine', to='journal.article')),
            ],
            options={
                'verbose_name': 'Numero de magazine',
                'verbose_name_plural': 'Numeros de magazine',
                'ordering': ['-date_publication', '-date_creation'],
            },
        ),
    ]
