# Generated by Django 6.0.5 on 2026-09-23 16:32

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_numeromagazine'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnBref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre court de la nouvelle urgente.', max_length=180)),
                ('texte', models.TextField(blank=True, help_text='Resume rapide en quelques phrases.')),
                ('photo', models.FileField(blank=True, upload_to='en_bref/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif'], message='Ajoutez une image valide: JPG, PNG, WEBP, AVIF ou GIF.')])),
                ('video', models.FileField(blank=True, help_text='Video MP4, WEBM, MOV ou M4V enregistree avec le telephone.', upload_to='en_bref/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v'], message='Ajoutez une video valide: MP4, WEBM, MOV ou M4V.')])),
                ('lien', models.URLField(blank=True, help_text='Lien facultatif vers un article complet ou une source.')),
                ('urgent', models.BooleanField(default=False)),
                ('publie', models.BooleanField(default=True)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'En bref',
                'verbose_name_plural': 'En bref',
                'ordering': ['-date_publication', '-date_creation'],
            },
        ),
    ]
